[package]
name = "vault-mev-api"
version = "0.2.1"
edition = "2021"
authors = [""]
description = "Agave Validator Plugin API for Vault MEV strategies"

[lib]
name = "vault_mev_api"
path = "src/lib.rs"

[dependencies]
ipc-channel = "0.20.2"
serde = { version = ">=1", features = ["derive"] }
solana-clock = { version = ">=3" }
solana-pubkey = { version = ">=3", features = ["serde"] }

[dev-dependencies]
bincode = "1"
